### ISSUE TITLE
Font Change to knob values

### ISSUE THREAD

**Issue by bjhindman** [fabricelacharme/KnobControl#1]
I have been unable to set the size of the font of the knob text.  Specifically, I mean the numbers that go around the perimeter of the knob to indicate a range of values (defaults to 1 through 100). They are small and I can't seem to change them either using the knob control's Font property under "Appearance" or the Font property under "KnobControl".

**Comment by fabricelacharme** [comment]
You can change now the size of the font of the knob text.

Font & Size selection for graduations:
 A new property ScaleFontAutoSize (bool) is available 
    * - false = no AutoSize => Allow font selection AND size of font.
    * - true = size of font is automaticly computetd as before.

Warning compatibility:
I have renamed 2 public variables 
* knobBackColor => KnobBackColor
* enum knobPointerStyle => KnobPointerStyles
